(setq-default requested-styles-list
	      '("anything"
		"mmm"
		"proofgeneral"
		"small-modes"
		"d"
		"factor"
		"gdb"
		"gnuplot"
		"haskell"
		"install-elisp"
		"agda"
		"javascript"
		"latex"
		"makefile"
		"micropython"
		"org"
		"python"
		"xml"
		"snippets"
		"html"
		"magit"
		"java"
                "c"
                "sml"
                "sage"
		))


(setq-default user-lisp-root (concat (getenv "HOME") "/emacsmoduler/"))
