(autoload 'longlines-mode "longlines" nil t)
(autoload 'hoogle-mode "hoogle" nil t)
(autoload 'xquery-mode "xquery-mode" nil t)
(autoload 'haml-mode "haml-mode" nil t)
(autoload 'erlang-mode "erlang" nil t)
(autoload 'peep-mode "peep" nil t)
(autoload 'speck-mode "speck" nil t)
(autoload 'russian-mode "russian-mode" nil t)
(load "small")

