(require 'repository-root) ; optional: needed for repository-wide search
(require 'grep-o-matic)
(setq grep-o-matic-repository-root-function 'repository-root)
(add-to-list 'repository-root-matchers repository-root-matcher/git)
(add-to-list 'repository-root-matchers repository-root-matcher/hg)
(add-to-list 'repository-root-matchers repository-root-matcher/darcs)
(add-to-list 'repository-root-matchers repository-root-matcher/autoconf)
(add-to-list 'repository-root-matchers repository-root-matcher/bzr)
(add-to-list 'repository-root-matchers repository-root-matcher/svn)
(add-to-list 'repository-root-matchers repository-root-matcher/cvs)
