(add-to-list 'load-path (concat grail-dist-elisp "org-mode/lisp/"))
(require 'org-install)
(setq org-log-done t)
(add-to-list 'auto-mode-alist '("\\.org\\'" . org-mode))
;(setq org-agenda-files (quote ("~/izmir/todo.org")))
